services:
  node:
    build:
      dockerfile: ./.devcontainer/node/DockerFile
    container_name: node
    stdin_open: true
    tty: true
  bun:
    build:
      dockerfile: ./.devcontainer/bun/DockerFile
    container_name: bun
    stdin_open: true
    tty: true
  java:
    build: 
      dockerfile: ./.devcontainer/java/DockerFile
    container_name: java
    stdin_open: true
    tty: true
  rust:
    build: 
      dockerfile: ./.devcontainer/rust/DockerFile
    container_name: rust
    stdin_open: true
    tty: true


